### ISSUE TITLE
Should IsValid(string) return false for values representing unknown

### ISSUE THREAD

**Issue by Corniel** [Qowaiv/Qowaiv#247]
Currently, the static methods `IsValid(string str)` return false for `null`, white-space, and if parsing that input would fail. However, with the same argument that a value representing the empty state is not valid (in the context of this method), you would argue that the unknown state should neither be valid.

What would you think?

**Comment by Neverfor** [comment]
I think that we might all agree, that state is not the same as value.

State can only be switched (assigned is a better word, but it is also used for values). In case, when it is not present, it is probably Unknown or Not Set, which is also a state.

When we talk about checking the input, then it becomes a value.

The check for IsValid (String.Empty) should therefore be based on:
> what is being checked: state or value (in our case, it's probably value)
> dotNet version
> if the setting used for nullables is enabled (with this setting, you see the warning, when it is possible for a nullable value to be passed to a non-nullable field).

Therefore:
if IsValid(string.Empty) and if IsValid(null) should return true for dotNet lower than 6 (I think it was 6, where they added it, but might have been 5).

if isValid(string.Empty) and if IsValid(null) should return false for dotNet 6 and above, unless Nullable setting is enabled for the project.

Why?
Becuase it will function the same way dotNet and Visual Studio work: it is possible to set a nullable value, but a warning will be given. It should also allow an intentional choice in architecture, where an empty prameter may be given and it must result in an exception.

Depending on the compiler, might be a bit crude, but the following compiles just fine:

string stringEmpty = string.Empty;
string stringNull = null;
string? stringAbsoluteNull = null;

Console.WriteLine(stringEmpty);
Console.WriteLine(stringNull);
Console.WriteLine(stringAbsoluteNull);

While the following will result in an error:

string nothing;
Console.WriteLine(nothing);

Yet, this will compile, if we explicitly set the object value, or rather - change the object state, because the value will remain the same. From the user's point of view, the value is set to another value, which happens to be the same (null), though: 

string nothing;
nothing = null;
Console.WriteLine(nothing);

If we look at this specific case, we can say that important part is the state. Ideally, you would also check if the item was updated, after it's creation. But this would go beyond the simple value check.

**Comment by pmdevers** [comment]
I think there is no right answer. It all depends on the buisness requirements what is valid. Therefor I would suggest to entirely drop the IsValid methods because of this.

**Comment by Corniel** [comment]
@pmdevers the more I think of it the more I'm in favor of dropping these statics too. Just use the SVO's. You always can decide if Empty/Unknown have any meaning for your domain.
